### ISSUE TITLE
Change to debian

### ISSUE THREAD

**Issue by PfiatDe** [rootcathacking/awscracknip#4]
Can we please move this to debian bookworm? 
Ubuntu is a pain. But I did not now, how the change the ami-id ;)
Thanks.

**Comment by rootcathacking** [comment]
done, I have not tested if the deployment from user-data still works

**Comment by PfiatDe** [comment]
The image id '[ami-04d481f6da046c1e2]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 2f051751-69de-470f-b648-788d7dc7758f; Proxy: null)
Nope :D
